/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 存活探针
         * @description 进程存活即返回 200，不检查外部依赖。
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 就绪探针
         * @description 检查数据库、缓存等依赖；任一依赖不可用时返回 503。
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 服务版本信息 */
        get: operations["getSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户名密码注册
         * @description 注册成功即视为登录，返回会话。用户名不区分大小写唯一。
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户名密码登录
         * @description 同一账号在同一网络连续失败 5 次、或在所有网络累计失败 20 次后锁定 15 分钟（`ACCOUNT_LOCKED`），短信登录可解除锁定。
         */
        post: operations["loginWithPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sms/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 发送登录或找回密码验证码
         * @description 同一手机号 60 秒内只能发送 1 条、每天最多 10 条，同一 IP 每小时最多 20 条，超出返回 `SMS_RATE_LIMITED`。
         *     找回密码时即使手机号未注册也返回成功（不发送），避免泄露手机号是否已注册。
         */
        post: operations["sendAuthSms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 手机号验证码登录
         * @description 手机号已绑定账号时直接登录；未绑定时返回注册凭证，客户端进入"完善注册"步骤。
         */
        post: operations["loginWithSms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 完善注册（短信登录的新手机号）
         * @description 使用短信登录返回的注册凭证设置用户名和密码，创建账号并自动绑定该手机号。凭证 10 分钟内有效且只能使用一次。
         */
        post: operations["completeSmsRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新令牌
         * @description 每次刷新都会轮换 Refresh Token，旧令牌随即失效。为容忍网络重试，刚被轮换的旧令牌在 30 秒内仍可再刷新一次；
         *     超过宽限期再次使用旧令牌会被视为令牌泄露，该设备会被强制下线。
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 通过手机号找回密码
         * @description 重置成功后该账号所有设备都会下线。
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 退出登录
         * @description 注销当前设备的会话。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前账号信息 */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改资料 */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v1/me/sms/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 发送账号操作验证码
         * @description - `bind_phone`：向待绑定的新手机号发送，需提供 `phone`。该号码已被其他账号绑定时同样返回成功但不发送，
         *       避免借此探测号码是否已注册；绑定时会因验证码无效而失败。
         *     - `verify_current`：向当前已绑定的手机号发送，用于换绑、修改密码、注销账号时验证身份。
         *
         *     频率限制与登录验证码相同。
         */
        post: operations["sendAccountSms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 修改密码
         * @description 需提供当前密码，或当前绑定手机号的验证码（`verify_current`）。修改成功后其他设备全部下线。
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 绑定或换绑手机号
         * @description 需要当前密码与新手机号的验证码（`bind_phone`）；已绑定手机号时为换绑，还需要当前手机号的验证码（`verify_current`）。
         *     验证码校验通过后号码仍被其他账号占用（并发绑定）时返回 `PHONE_TAKEN`。
         */
        put: operations["bindPhone"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/deletion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 注销账号
         * @description 永久删除账号及其全部数据，不可恢复。需提供当前密码，或当前绑定手机号的验证码（`verify_current`）。
         */
        post: operations["deleteAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 已登录设备 */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 将设备下线
         * @description 该设备的令牌立即失效。不能用此接口下线当前设备（请使用退出登录）。
         */
        delete: operations["revokeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户设置 */
        get: operations["getSettings"];
        /** 保存用户设置 */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/e2e/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 建立传输加密会话
         * @description 客户端生成临时 X25519 密钥对并上传公钥，双方各自派生会话密钥（ADR-006）。
         *     之后的推送、拉取、修订和附件接口用请求头 `X-JikeLog-E2E` 携带返回的会话 ID，敏感字段以该会话加密。
         *     会话绑定当前设备，24 小时后失效；失效时接口返回 409 `E2E_SESSION_INVALID`，重新握手即可。
         *     `serverKeyId` 不再受支持时返回 409 `E2E_KEY_UNKNOWN`，需要升级 App。
         */
        post: operations["createE2ESession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 推送本地变更
         * @description 每条变更只带改过的字段及其 HLC，`baseClocks` 为修改前最后一次从服务端拿到的字段时钟。
         *     单条变更校验失败只拒绝这一条（`rejected`），不影响同批其他变更。结果为 `merged` 或 `conflict` 时返回服务端最终记录，客户端用它覆盖本地。
         *     实时通知：`GET /api/v1/sync/ws`（需登录，升级为 WebSocket），服务端推送 `{"type":"hello"|"changed","seq":…,"origin":…}`，
         *     设备下线后以关闭码 4401 断开。
         */
        post: operations["pushChanges"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 增量拉取
         * @description 按 `serverSeq` 升序返回大于 `since` 的记录（含墓碑，墓碑不含字段）。`hasMore` 为 true 时以 `nextSince` 继续拉取。
         */
        get: operations["pullChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 确认已处理的同步序号 */
        post: operations["ackSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{recordId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 修订历史
         * @description 新的在前，不含内容。原因：edit（编辑前的状态）、conflict（冲突中落败的一方）、delete（删除前的状态）。
         */
        get: operations["listRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/revisions/{revisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 修订内容
         * @description 恢复某个版本即以修订内容做一次普通编辑并推送。
         */
        get: operations["getRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 申请上传附件
         * @description 返回对象存储的预签名直传地址：客户端用 `PUT` 上传，并原样带上 `headers`（大小与类型已纳入签名）。
         *     上传完成后调用 complete，服务端核对大小并生成 attachment 同步记录。
         *     单个附件与每个账号的总量有上限（见 usage），超出时返回 413 `ATTACHMENT_TOO_LARGE` / `QUOTA_EXCEEDED`。
         */
        post: operations["createAttachmentUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attachments/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 附件用量 */
        get: operations["getAttachmentUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attachments/{attachmentId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 确认上传完成
         * @description 对象尚未上传或大小不符时返回 409 `UPLOAD_INCOMPLETE`。重复调用是幂等的。
         */
        post: operations["completeAttachmentUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attachments/{attachmentId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取下载地址 */
        get: operations["getAttachmentDownload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            /**
             * @description 机器可读错误码
             * @example VALIDATION_FAILED
             */
            code: string;
            /**
             * @description 面向用户的错误描述
             * @example 参数校验失败
             */
            message: string;
            /** @description 附加信息，如字段级校验错误 */
            details?: {
                [key: string]: unknown;
            };
        };
        PageMeta: {
            /** Format: int64 */
            total: number;
            page: number;
            limit: number;
        };
        EnvelopeBase: {
            success: boolean;
            error?: components["schemas"]["ErrorBody"];
            meta?: components["schemas"]["PageMeta"];
            /** @description 请求 ID，与响应头 X-Request-ID 一致，便于排查 */
            requestId: string;
        };
        ErrorEnvelope: components["schemas"]["EnvelopeBase"] & {
            error: components["schemas"]["ErrorBody"];
        };
        HealthCheck: {
            /** @example postgres */
            name: string;
            /** @enum {string} */
            status: "up" | "down";
            error?: string;
        };
        Health: {
            /** @enum {string} */
            status: "up" | "down";
            checks: components["schemas"]["HealthCheck"][];
        };
        HealthEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["Health"];
        };
        SystemInfo: {
            /** @example jikelog-api */
            name: string;
            /** @example 0.1.0 */
            version: string;
            commit: string;
            buildTime: string;
            /** Format: date-time */
            serverTime: string;
        };
        SystemInfoEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["SystemInfo"];
        };
        Ack: {
            ok: boolean;
        };
        AckEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["Ack"];
        };
        /**
         * @description 4–20 位，字母开头，只含字母、数字、下划线；不区分大小写唯一
         * @example zhang_san
         */
        Username: string;
        /**
         * Format: password
         * @description 8–128 位，至少包含字母和数字
         */
        Password: string;
        /**
         * @description 中国大陆手机号，可带 +86 前缀
         * @example 13812345678
         */
        Phone: string;
        /** @description 6 位数字验证码，5 分钟内有效，最多尝试 5 次 */
        SmsCode: string;
        /** @description 昵称，最多 20 个字符 */
        Nickname: string;
        /** @description 客户端设备信息。`installationId` 由客户端首次启动时生成并持久保存，同一安装实例重复登录同一账号时复用设备记录。 */
        DeviceInfo: {
            installationId: string;
            /** @enum {string} */
            platform: "android" | "ios" | "windows" | "macos" | "linux" | "web";
            /** @example Xiaomi 14 */
            model?: string;
            /** @example Android 15 */
            osVersion?: string;
            /** @example 0.2.0 */
            appVersion?: string;
        };
        RegisterRequest: {
            username: components["schemas"]["Username"];
            password: components["schemas"]["Password"];
            nickname?: components["schemas"]["Nickname"];
            device: components["schemas"]["DeviceInfo"];
        };
        PasswordLoginRequest: {
            username: string;
            /** Format: password */
            password: string;
            device: components["schemas"]["DeviceInfo"];
        };
        /** @enum {string} */
        SmsPurpose: "login" | "reset_password";
        AuthSmsRequest: {
            phone: components["schemas"]["Phone"];
            purpose: components["schemas"]["SmsPurpose"];
            /** @description 人机验证结果（阿里云验证码 2.0），开发环境可省略 */
            captchaVerifyParam?: string;
        };
        /** @enum {string} */
        AccountSmsPurpose: "bind_phone" | "verify_current";
        AccountSmsRequest: {
            purpose: components["schemas"]["AccountSmsPurpose"];
            phone?: components["schemas"]["Phone"];
            captchaVerifyParam?: string;
        };
        SmsSent: {
            /**
             * @description 距离可再次发送的秒数
             * @example 60
             */
            cooldownSeconds: number;
            /**
             * @description 验证码有效期（秒）
             * @example 300
             */
            expiresInSeconds: number;
        };
        SmsSentEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["SmsSent"];
        };
        SmsLoginRequest: {
            phone: components["schemas"]["Phone"];
            code: components["schemas"]["SmsCode"];
            device: components["schemas"]["DeviceInfo"];
        };
        SmsLoginResult: {
            /** @enum {string} */
            status: "authenticated" | "registration_required";
            session?: components["schemas"]["AuthSession"];
            /** @description status 为 registration_required 时返回，用于完善注册 */
            registrationTicket?: string;
            /**
             * @description status 为 registration_required 时返回，供界面展示
             * @example 138****5678
             */
            phoneMasked?: string;
        };
        SmsLoginResultEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["SmsLoginResult"];
        };
        CompleteSmsRegistrationRequest: {
            registrationTicket: string;
            username: components["schemas"]["Username"];
            password: components["schemas"]["Password"];
            nickname?: components["schemas"]["Nickname"];
            device: components["schemas"]["DeviceInfo"];
        };
        RefreshRequest: {
            refreshToken: string;
        };
        ResetPasswordRequest: {
            phone: components["schemas"]["Phone"];
            code: components["schemas"]["SmsCode"];
            newPassword: components["schemas"]["Password"];
        };
        TokenPair: {
            /** @enum {string} */
            tokenType: "Bearer";
            accessToken: string;
            /** Format: date-time */
            accessExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshExpiresAt: string;
        };
        TokenPairEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["TokenPair"];
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            nickname: string;
            hasPhone: boolean;
            /**
             * @description 脱敏后的手机号，未绑定时不返回
             * @example 138****5678
             */
            phoneMasked?: string;
            /** Format: date-time */
            createdAt: string;
        };
        UserEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["User"];
        };
        AuthSession: {
            user: components["schemas"]["User"];
            tokens: components["schemas"]["TokenPair"];
            /**
             * Format: uuid
             * @description 服务端为本次登录分配的设备 ID
             */
            deviceId: string;
        };
        AuthSessionEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["AuthSession"];
        };
        UpdateMeRequest: {
            nickname: components["schemas"]["Nickname"];
        };
        /** @description 当前密码与当前手机号验证码二选一 */
        VerifyIdentityRequest: {
            /** Format: password */
            currentPassword?: string;
            smsCode?: components["schemas"]["SmsCode"];
        };
        ChangePasswordRequest: components["schemas"]["VerifyIdentityRequest"] & {
            newPassword: components["schemas"]["Password"];
        };
        BindPhoneRequest: {
            phone: components["schemas"]["Phone"];
            code: components["schemas"]["SmsCode"];
            /**
             * Format: password
             * @description 当前密码，防止他人用被盗的登录态绑定自己的号码接管账号
             */
            currentPassword: string;
            currentCode?: components["schemas"]["SmsCode"];
        };
        Device: {
            /** Format: uuid */
            id: string;
            platform: string;
            model: string;
            osVersion: string;
            appVersion: string;
            /** Format: date-time */
            lastActiveAt: string;
            /** Format: date-time */
            createdAt: string;
            /** @description 是否为发起请求的设备 */
            current: boolean;
        };
        DeviceListEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["Device"][];
        };
        /** @enum {string} */
        ThemeMode: "system" | "light" | "dark";
        SettingsInput: {
            themeMode: components["schemas"]["ThemeMode"];
            /**
             * Format: float
             * @description 字号缩放
             */
            fontScale: number;
            /** @description 新建备忘录时默认的提前提醒（分钟，0 表示准时），不超过 30 天 */
            defaultReminders: number[];
            /**
             * @description 一周的第一天：1 = 周一，7 = 周日
             * @enum {integer}
             */
            weekStart: 1 | 7;
        };
        Settings: components["schemas"]["SettingsInput"] & {
            /** Format: date-time */
            updatedAt: string;
        };
        SettingsEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["Settings"];
        };
        E2ESessionRequest: {
            /** @description 客户端临时 X25519 公钥（标准 base64，32 字节） */
            clientPublicKey: string;
            /** @description App 内置服务端公钥的标识（SHA-256 前 8 字节的十六进制） */
            serverKeyId: string;
        };
        E2ESession: {
            sessionId: string;
            /** Format: date-time */
            expiresAt: string;
        };
        E2ESessionEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["E2ESession"];
        };
        SyncChange: {
            /** @description 实体类型：worklog（工作日志）、note（笔记）、note_folder（笔记文件夹）、attachment（附件，只能删除）。字段定义见 ADR-005、ADR-007 */
            entity: string;
            /**
             * Format: uuid
             * @description 客户端生成的 UUIDv7
             */
            id: string;
            /** @description 为 true 时删除记录（墓碑） */
            deleted?: boolean;
            /** @description 改过的字段：字符串、整数或 null；敏感字段为传输密文（AAD 以 `|v` 结尾） */
            fields?: {
                [key: string]: unknown;
            };
            /** @description 改过字段的混合逻辑时钟（HLC）`<13 位毫秒>-<4 位十六进制计数>-<16 位十六进制节点>` */
            clocks?: {
                [key: string]: string;
            };
            /** @description 修改前最后一次从服务端拿到的字段时钟 */
            baseClocks?: {
                [key: string]: string;
            };
            /** @description 长文本字段相对基准文本的补丁（JSON 字符串）；敏感字段为传输密文（AAD 以 `|p` 结尾） */
            patches?: {
                [key: string]: string;
            };
        };
        PushRequest: {
            changes: components["schemas"]["SyncChange"][];
        };
        SyncRecord: {
            entity: string;
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            version: number;
            /** Format: int64 */
            serverSeq: number;
            deleted: boolean;
            /** @description 字段值；敏感字段为传输密文。墓碑为空对象 */
            fields: {
                [key: string]: unknown;
            };
            clocks: {
                [key: string]: string;
            };
            /** Format: date-time */
            updatedAt: string;
        };
        ChangeError: {
            /** @description VALIDATION_FAILED / UNKNOWN_ENTITY / CLOCK_SKEW / ID_CONFLICT / E2E_DECRYPT_FAILED */
            code: string;
            message: string;
            fields?: {
                [key: string]: string;
            };
        };
        PushResult: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "applied" | "merged" | "conflict" | "rejected";
            /** Format: int64 */
            version?: number;
            /** Format: int64 */
            serverSeq?: number;
            record?: components["schemas"]["SyncRecord"];
            error?: components["schemas"]["ChangeError"];
        };
        PushResponse: {
            results: components["schemas"]["PushResult"][];
            /**
             * Format: int64
             * @description 处理后账号的同步序号
             */
            cursor: number;
        };
        PushEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["PushResponse"];
        };
        PullResponse: {
            records: components["schemas"]["SyncRecord"][];
            /** Format: int64 */
            nextSince: number;
            hasMore: boolean;
        };
        PullEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["PullResponse"];
        };
        AckRequest: {
            /** Format: int64 */
            seq: number;
        };
        RevisionInfo: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            version: number;
            /** @enum {string} */
            reason: "edit" | "conflict" | "delete";
            /** Format: date-time */
            createdAt: string;
            /** @description 产生该修订的设备型号，设备已删除时为空 */
            deviceModel: string;
        };
        RevisionListEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["RevisionInfo"][];
        };
        Revision: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            recordId: string;
            entity: string;
            /** Format: int64 */
            version: number;
            /** @enum {string} */
            reason: "edit" | "conflict" | "delete";
            /** Format: date-time */
            createdAt: string;
            /** @description 字段值；敏感字段为传输密文 */
            fields: {
                [key: string]: unknown;
            };
        };
        RevisionEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["Revision"];
        };
        AttachmentUploadRequest: {
            /**
             * Format: uuid
             * @description 客户端生成的 UUIDv7，同时作为 attachment 同步记录的 ID
             */
            id: string;
            /** @description 所属记录的实体类型，只能是 worklog 或 note */
            ownerEntity: string;
            /** Format: uuid */
            ownerId: string;
            /** @description 文件名的传输密文（AAD 为 `jikelog-e2e-v1|attachment|<id>|fileName|v`） */
            fileName: string;
            /** @example image/jpeg */
            mime: string;
            /** Format: int64 */
            size: number;
            /** @description 文件内容的 SHA-256（小写十六进制），下载后客户端据此校验 */
            sha256: string;
        };
        AttachmentUpload: {
            uploadUrl: string;
            /** @enum {string} */
            method: "PUT";
            headers: {
                [key: string]: string;
            };
            /** Format: date-time */
            expiresAt: string;
        };
        AttachmentUploadEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["AttachmentUpload"];
        };
        AttachmentComplete: {
            /** Format: int64 */
            serverSeq: number;
        };
        AttachmentCompleteEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["AttachmentComplete"];
        };
        AttachmentDownload: {
            url: string;
            /** Format: date-time */
            expiresAt: string;
        };
        AttachmentDownloadEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["AttachmentDownload"];
        };
        AttachmentUsage: {
            /** Format: int64 */
            used: number;
            /** Format: int64 */
            quota: number;
            /** Format: int64 */
            maxSize: number;
        };
        AttachmentUsageEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["AttachmentUsage"];
        };
    };
    responses: {
        /** @description 错误（4xx/5xx），统一使用错误信封 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description 传输加密会话 ID（见 createE2ESession）；请求或响应含敏感字段时必须携带 */
        E2ESessionHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 就绪 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
            /** @description 依赖不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    loginWithPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordLoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    sendAuthSms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthSmsRequest"];
            };
        };
        responses: {
            /** @description 已受理 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmsSentEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    loginWithSms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmsLoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功或需要完善注册 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmsLoginResultEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    completeSmsRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteSmsRegistrationRequest"];
            };
        };
        responses: {
            /** @description 注册成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 新的令牌 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description 重置成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已退出 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 账号信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description 修改后的账号信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    sendAccountSms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountSmsRequest"];
            };
        };
        responses: {
            /** @description 已发送 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmsSentEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description 修改成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    bindPhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindPhoneRequest"];
            };
        };
        responses: {
            /** @description 绑定后的账号信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyIdentityRequest"];
            };
        };
        responses: {
            /** @description 已注销 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 按最近活跃排序的设备列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已下线 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户设置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsInput"];
            };
        };
        responses: {
            /** @description 保存后的设置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createE2ESession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["E2ESessionRequest"];
            };
        };
        responses: {
            /** @description 已建立 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["E2ESessionEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    pushChanges: {
        parameters: {
            query?: never;
            header?: {
                /** @description 传输加密会话 ID（见 createE2ESession）；请求或响应含敏感字段时必须携带 */
                "X-JikeLog-E2E"?: components["parameters"]["E2ESessionHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRequest"];
            };
        };
        responses: {
            /** @description 逐条处理结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    pullChanges: {
        parameters: {
            query: {
                since: number;
                limit?: number;
            };
            header?: {
                /** @description 传输加密会话 ID（见 createE2ESession）；请求或响应含敏感字段时必须携带 */
                "X-JikeLog-E2E"?: components["parameters"]["E2ESessionHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 一页记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    ackSync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AckRequest"];
            };
        };
        responses: {
            /** @description 已记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 修订列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionListEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRevision: {
        parameters: {
            query?: never;
            header?: {
                /** @description 传输加密会话 ID（见 createE2ESession）；请求或响应含敏感字段时必须携带 */
                "X-JikeLog-E2E"?: components["parameters"]["E2ESessionHeader"];
            };
            path: {
                revisionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 修订详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createAttachmentUpload: {
        parameters: {
            query?: never;
            header?: {
                /** @description 传输加密会话 ID（见 createE2ESession）；请求或响应含敏感字段时必须携带 */
                "X-JikeLog-E2E"?: components["parameters"]["E2ESessionHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachmentUploadRequest"];
            };
        };
        responses: {
            /** @description 上传地址 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentUploadEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAttachmentUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用量与上限 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentUsageEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    completeAttachmentUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已生成同步记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentCompleteEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAttachmentDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 预签名下载地址（10 分钟内有效） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentDownloadEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
