/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 存活探针
         * @description 进程存活即返回 200，不检查外部依赖。
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 就绪探针
         * @description 检查数据库、缓存等依赖；任一依赖不可用时返回 503。
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 服务版本信息 */
        get: operations["getSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            /**
             * @description 机器可读错误码
             * @example VALIDATION_FAILED
             */
            code: string;
            /**
             * @description 面向用户的错误描述
             * @example 参数校验失败
             */
            message: string;
            /** @description 附加信息，如字段级校验错误 */
            details?: {
                [key: string]: unknown;
            };
        };
        PageMeta: {
            /** Format: int64 */
            total: number;
            page: number;
            limit: number;
        };
        EnvelopeBase: {
            success: boolean;
            error?: components["schemas"]["ErrorBody"];
            meta?: components["schemas"]["PageMeta"];
            /** @description 请求 ID，与响应头 X-Request-ID 一致，便于排查 */
            requestId: string;
        };
        ErrorEnvelope: components["schemas"]["EnvelopeBase"] & {
            error: components["schemas"]["ErrorBody"];
        };
        HealthCheck: {
            /** @example postgres */
            name: string;
            /** @enum {string} */
            status: "up" | "down";
            error?: string;
        };
        Health: {
            /** @enum {string} */
            status: "up" | "down";
            checks: components["schemas"]["HealthCheck"][];
        };
        HealthEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["Health"];
        };
        SystemInfo: {
            /** @example jikelog-api */
            name: string;
            /** @example 0.1.0 */
            version: string;
            commit: string;
            buildTime: string;
            /** Format: date-time */
            serverTime: string;
        };
        SystemInfoEnvelope: components["schemas"]["EnvelopeBase"] & {
            data: components["schemas"]["SystemInfo"];
        };
    };
    responses: {
        /** @description 错误（4xx/5xx），统一使用错误信封 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 就绪 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
            /** @description 依赖不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoEnvelope"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
