// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDefaultSettings = `-- name: CreateDefaultSettings :exec
INSERT INTO user_settings (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) CreateDefaultSettings(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createDefaultSettings, userID)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, username, nickname, phone, password_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, nickname, phone, password_hash, password_changed_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	Username     string
	Nickname     string
	Phone        *string
	PasswordHash string
}

// 账号、设备与设置相关查询，由 sqlc 生成到 internal/dbgen（scripts/gen-db.sh）。
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Nickname,
		arg.Phone,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Phone,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, installation_id, platform, model, os_version, app_version, refresh_hash, refresh_prev_hash, refresh_rotated_at, refresh_expires_at, last_ip, last_active_at, created_at, tokens_valid_after, revoked_at, last_ack_seq FROM devices WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.Platform,
		&i.Model,
		&i.OsVersion,
		&i.AppVersion,
		&i.RefreshHash,
		&i.RefreshPrevHash,
		&i.RefreshRotatedAt,
		&i.RefreshExpiresAt,
		&i.LastIp,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.TokensValidAfter,
		&i.RevokedAt,
		&i.LastAckSeq,
	)
	return i, err
}

const getDeviceByRefreshHashForUpdate = `-- name: GetDeviceByRefreshHashForUpdate :one
SELECT id, user_id, installation_id, platform, model, os_version, app_version, refresh_hash, refresh_prev_hash, refresh_rotated_at, refresh_expires_at, last_ip, last_active_at, created_at, tokens_valid_after, revoked_at, last_ack_seq FROM devices
WHERE (refresh_hash = $1 OR refresh_prev_hash = $1) AND revoked_at IS NULL
LIMIT 1
FOR UPDATE
`

// 同时匹配当前与上一枚 Refresh Token，由调用方区分正常刷新、并发宽限与重放。
func (q *Queries) GetDeviceByRefreshHashForUpdate(ctx context.Context, hash []byte) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByRefreshHashForUpdate, hash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.Platform,
		&i.Model,
		&i.OsVersion,
		&i.AppVersion,
		&i.RefreshHash,
		&i.RefreshPrevHash,
		&i.RefreshRotatedAt,
		&i.RefreshExpiresAt,
		&i.LastIp,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.TokensValidAfter,
		&i.RevokedAt,
		&i.LastAckSeq,
	)
	return i, err
}

const getDeviceSession = `-- name: GetDeviceSession :one
SELECT user_id, tokens_valid_after FROM devices WHERE id = $1 AND revoked_at IS NULL
`

type GetDeviceSessionRow struct {
	UserID           uuid.UUID
	TokensValidAfter time.Time
}

// 认证中间件每个请求调用一次（主键查询）。
func (q *Queries) GetDeviceSession(ctx context.Context, id uuid.UUID) (GetDeviceSessionRow, error) {
	row := q.db.QueryRow(ctx, getDeviceSession, id)
	var i GetDeviceSessionRow
	err := row.Scan(&i.UserID, &i.TokensValidAfter)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT user_id, theme_mode, font_scale, default_reminders, week_start, updated_at FROM user_settings WHERE user_id = $1
`

func (q *Queries) GetSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.ThemeMode,
		&i.FontScale,
		&i.DefaultReminders,
		&i.WeekStart,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, nickname, phone, password_hash, password_changed_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Phone,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, username, nickname, phone, password_hash, password_changed_at, created_at, updated_at FROM users WHERE phone = $1::text
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Phone,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, nickname, phone, password_hash, password_changed_at, created_at, updated_at FROM users WHERE lower(username) = lower($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Phone,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDevices = `-- name: ListActiveDevices :many
SELECT id, user_id, installation_id, platform, model, os_version, app_version, refresh_hash, refresh_prev_hash, refresh_rotated_at, refresh_expires_at, last_ip, last_active_at, created_at, tokens_valid_after, revoked_at, last_ack_seq FROM devices
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY last_active_at DESC
`

func (q *Queries) ListActiveDevices(ctx context.Context, userID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listActiveDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstallationID,
			&i.Platform,
			&i.Model,
			&i.OsVersion,
			&i.AppVersion,
			&i.RefreshHash,
			&i.RefreshPrevHash,
			&i.RefreshRotatedAt,
			&i.RefreshExpiresAt,
			&i.LastIp,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.TokensValidAfter,
			&i.RevokedAt,
			&i.LastAckSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllDevices = `-- name: RevokeAllDevices :many
UPDATE devices
SET revoked_at = $1::timestamptz, tokens_valid_after = $1::timestamptz, refresh_hash = NULL, refresh_prev_hash = NULL
WHERE user_id = $2 AND revoked_at IS NULL
RETURNING id
`

type RevokeAllDevicesParams struct {
	Now    time.Time
	UserID uuid.UUID
}

func (q *Queries) RevokeAllDevices(ctx context.Context, arg RevokeAllDevicesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeAllDevices, arg.Now, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :many
UPDATE devices
SET revoked_at = $1::timestamptz, tokens_valid_after = $1::timestamptz, refresh_hash = NULL, refresh_prev_hash = NULL
WHERE id = $2 AND user_id = $3 AND revoked_at IS NULL
RETURNING id
`

type RevokeDeviceParams struct {
	Now    time.Time
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeDevice, arg.Now, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOtherDevices = `-- name: RevokeOtherDevices :many
UPDATE devices
SET revoked_at = $1::timestamptz, tokens_valid_after = $1::timestamptz, refresh_hash = NULL, refresh_prev_hash = NULL
WHERE user_id = $2 AND id <> $3 AND revoked_at IS NULL
RETURNING id
`

type RevokeOtherDevicesParams struct {
	Now    time.Time
	UserID uuid.UUID
	KeepID uuid.UUID
}

func (q *Queries) RevokeOtherDevices(ctx context.Context, arg RevokeOtherDevicesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeOtherDevices, arg.Now, arg.UserID, arg.KeepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeviceRefresh = `-- name: SetDeviceRefresh :exec
UPDATE devices SET
    refresh_hash       = $1,
    refresh_prev_hash  = $2,
    refresh_rotated_at = $3,
    refresh_expires_at = $4,
    last_ip            = $5,
    last_active_at     = now()
WHERE id = $6
`

type SetDeviceRefreshParams struct {
	RefreshHash      []byte
	RefreshPrevHash  []byte
	RefreshRotatedAt *time.Time
	RefreshExpiresAt *time.Time
	LastIp           string
	ID               uuid.UUID
}

func (q *Queries) SetDeviceRefresh(ctx context.Context, arg SetDeviceRefreshParams) error {
	_, err := q.db.Exec(ctx, setDeviceRefresh,
		arg.RefreshHash,
		arg.RefreshPrevHash,
		arg.RefreshRotatedAt,
		arg.RefreshExpiresAt,
		arg.LastIp,
		arg.ID,
	)
	return err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE user_settings SET
    theme_mode        = $1,
    font_scale        = $2,
    default_reminders = $3,
    week_start        = $4,
    updated_at        = now()
WHERE user_id = $5
RETURNING user_id, theme_mode, font_scale, default_reminders, week_start, updated_at
`

type UpdateSettingsParams struct {
	ThemeMode        string
	FontScale        float32
	DefaultReminders []int32
	WeekStart        int16
	UserID           uuid.UUID
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updateSettings,
		arg.ThemeMode,
		arg.FontScale,
		arg.DefaultReminders,
		arg.WeekStart,
		arg.UserID,
	)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.ThemeMode,
		&i.FontScale,
		&i.DefaultReminders,
		&i.WeekStart,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserNickname = `-- name: UpdateUserNickname :one
UPDATE users SET nickname = $1, updated_at = now() WHERE id = $2
RETURNING id, username, nickname, phone, password_hash, password_changed_at, created_at, updated_at
`

type UpdateUserNicknameParams struct {
	Nickname string
	ID       uuid.UUID
}

func (q *Queries) UpdateUserNickname(ctx context.Context, arg UpdateUserNicknameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserNickname, arg.Nickname, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Nickname,
		&i.Phone,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1, password_changed_at = now(), updated_at = now()
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           uuid.UUID
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users SET password_hash = $1 WHERE id = $2 AND password_hash = $3
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string
	ID           uuid.UUID
	OldHash      string
}

// 仅升级哈希参数（密码本身未变），不更新 password_changed_at；旧哈希不符说明密码已被并发修改，放弃升级。
func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.PasswordHash, arg.ID, arg.OldHash)
	return err
}

const updateUserPhone = `-- name: UpdateUserPhone :exec
UPDATE users SET phone = $1, updated_at = now() WHERE id = $2
`

type UpdateUserPhoneParams struct {
	Phone *string
	ID    uuid.UUID
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error {
	_, err := q.db.Exec(ctx, updateUserPhone, arg.Phone, arg.ID)
	return err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (
    id, user_id, installation_id, platform, model, os_version, app_version,
    refresh_hash, refresh_rotated_at, refresh_expires_at, last_ip, tokens_valid_after
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9::timestamptz, $10, $11, $9::timestamptz
)
ON CONFLICT (user_id, installation_id) DO UPDATE SET
    platform           = EXCLUDED.platform,
    model              = EXCLUDED.model,
    os_version         = EXCLUDED.os_version,
    app_version        = EXCLUDED.app_version,
    refresh_hash       = EXCLUDED.refresh_hash,
    refresh_prev_hash  = NULL,
    refresh_rotated_at = EXCLUDED.refresh_rotated_at,
    refresh_expires_at = EXCLUDED.refresh_expires_at,
    last_ip            = EXCLUDED.last_ip,
    last_active_at     = now(),
    -- 新会话：此前签发给该设备的令牌全部作废
    tokens_valid_after = EXCLUDED.tokens_valid_after,
    revoked_at         = NULL
RETURNING id, user_id, installation_id, platform, model, os_version, app_version, refresh_hash, refresh_prev_hash, refresh_rotated_at, refresh_expires_at, last_ip, last_active_at, created_at, tokens_valid_after, revoked_at, last_ack_seq
`

type UpsertDeviceParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	InstallationID   string
	Platform         string
	Model            string
	OsVersion        string
	AppVersion       string
	RefreshHash      []byte
	Now              time.Time
	RefreshExpiresAt *time.Time
	LastIp           string
}

// 同一安装实例再次登录同一账号时复用设备行：重新激活、更新设备信息并换发 Refresh Token。
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.ID,
		arg.UserID,
		arg.InstallationID,
		arg.Platform,
		arg.Model,
		arg.OsVersion,
		arg.AppVersion,
		arg.RefreshHash,
		arg.Now,
		arg.RefreshExpiresAt,
		arg.LastIp,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.Platform,
		&i.Model,
		&i.OsVersion,
		&i.AppVersion,
		&i.RefreshHash,
		&i.RefreshPrevHash,
		&i.RefreshRotatedAt,
		&i.RefreshExpiresAt,
		&i.LastIp,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.TokensValidAfter,
		&i.RevokedAt,
		&i.LastAckSeq,
	)
	return i, err
}
