// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT count(*) FROM users u
WHERE $1::text = ''
   OR u.username ILIKE '%' || $1::text || '%'
   OR u.nickname ILIKE '%' || $1::text || '%'
   OR ($2::text <> '' AND u.phone LIKE '%' || $2::text)
`

type AdminCountUsersParams struct {
	Query       string
	PhoneSuffix string
}

func (q *Queries) AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers, arg.Query, arg.PhoneSuffix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminDailyNewUsers = `-- name: AdminDailyNewUsers :many
SELECT to_char(created_at AT TIME ZONE $1::text, 'YYYY-MM-DD')::text AS day, count(*)::bigint AS users
FROM users
WHERE created_at >= $2
GROUP BY day
ORDER BY day
`

type AdminDailyNewUsersParams struct {
	Tz    string
	Since time.Time
}

type AdminDailyNewUsersRow struct {
	Day   string
	Users int64
}

// 每天新增的用户数（按给定时区的日期）。
func (q *Queries) AdminDailyNewUsers(ctx context.Context, arg AdminDailyNewUsersParams) ([]AdminDailyNewUsersRow, error) {
	rows, err := q.db.Query(ctx, adminDailyNewUsers, arg.Tz, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminDailyNewUsersRow{}
	for rows.Next() {
		var i AdminDailyNewUsersRow
		if err := rows.Scan(&i.Day, &i.Users); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminLastSync = `-- name: AdminLastSync :one
SELECT updated_at FROM records WHERE user_id = $1 ORDER BY updated_at DESC LIMIT 1
`

// 最后一次有记录写入服务端的时间（不含内容）；没有任何记录时查不到。
func (q *Queries) AdminLastSync(ctx context.Context, userID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, adminLastSync, userID)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const adminListUserDevices = `-- name: AdminListUserDevices :many
SELECT id, platform, model, os_version, app_version, last_active_at, created_at, revoked_at,
       local_reminders, last_ack_seq, (push_token IS NOT NULL)::boolean AS push_enabled
FROM devices
WHERE user_id = $1
ORDER BY revoked_at IS NOT NULL, last_active_at DESC
`

type AdminListUserDevicesRow struct {
	ID             uuid.UUID
	Platform       string
	Model          string
	OsVersion      string
	AppVersion     string
	LastActiveAt   time.Time
	CreatedAt      time.Time
	RevokedAt      *time.Time
	LocalReminders bool
	LastAckSeq     int64
	PushEnabled    bool
}

func (q *Queries) AdminListUserDevices(ctx context.Context, userID uuid.UUID) ([]AdminListUserDevicesRow, error) {
	rows, err := q.db.Query(ctx, adminListUserDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUserDevicesRow{}
	for rows.Next() {
		var i AdminListUserDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Model,
			&i.OsVersion,
			&i.AppVersion,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.LocalReminders,
			&i.LastAckSeq,
			&i.PushEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many

SELECT
    u.id, u.username, u.nickname, u.phone, u.created_at,
    -- 没有设备（全部退出且被清理）时以注册时间代替
    COALESCE((SELECT max(d.last_active_at) FROM devices d WHERE d.user_id = u.id), u.created_at)::timestamptz AS last_active_at,
    (SELECT count(*) FROM devices d WHERE d.user_id = u.id AND d.revoked_at IS NULL)::bigint AS device_count,
    (SELECT COALESCE(SUM(a.size), 0) FROM attachments a WHERE a.user_id = u.id AND a.status <> 'deleted')::bigint AS storage_bytes
FROM users u
WHERE $1::text = ''
   OR u.username ILIKE '%' || $1::text || '%'
   OR u.nickname ILIKE '%' || $1::text || '%'
   OR ($2::text <> '' AND u.phone LIKE '%' || $2::text)
ORDER BY u.created_at DESC, u.id
LIMIT $4 OFFSET $3
`

type AdminListUsersParams struct {
	Query       string
	PhoneSuffix string
	Skip        int32
	MaxRows     int32
}

type AdminListUsersRow struct {
	ID           uuid.UUID
	Username     string
	Nickname     string
	Phone        *string
	CreatedAt    time.Time
	LastActiveAt time.Time
	DeviceCount  int64
	StorageBytes int64
}

// ───────────── 用户 ─────────────
// 用户列表：按用户名、昵称或手机号后几位搜索，新注册的在前。
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers,
		arg.Query,
		arg.PhoneSuffix,
		arg.Skip,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Nickname,
			&i.Phone,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.DeviceCount,
			&i.StorageBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPlatformStats = `-- name: AdminPlatformStats :many
SELECT platform, count(*)::bigint AS devices
FROM devices
WHERE revoked_at IS NULL AND last_active_at >= $1
GROUP BY platform
ORDER BY devices DESC
`

type AdminPlatformStatsRow struct {
	Platform string
	Devices  int64
}

// 最近活跃的已登录设备的平台分布。
func (q *Queries) AdminPlatformStats(ctx context.Context, since time.Time) ([]AdminPlatformStatsRow, error) {
	rows, err := q.db.Query(ctx, adminPlatformStats, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminPlatformStatsRow{}
	for rows.Next() {
		var i AdminPlatformStatsRow
		if err := rows.Scan(&i.Platform, &i.Devices); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUserStats = `-- name: AdminUserStats :one

SELECT
    (SELECT count(*) FROM users)::bigint AS total,
    (SELECT count(*) FROM users WHERE created_at >= $1::timestamptz)::bigint AS new_today,
    (SELECT count(DISTINCT user_id) FROM devices WHERE last_active_at >= $1::timestamptz)::bigint AS active_today,
    (SELECT count(DISTINCT user_id) FROM devices WHERE last_active_at >= $2::timestamptz)::bigint AS active_week,
    (SELECT count(DISTINCT user_id) FROM devices WHERE last_active_at >= $3::timestamptz)::bigint AS active_month,
    (SELECT COALESCE(SUM(size), 0) FROM attachments WHERE status <> 'deleted')::bigint AS storage_bytes
`

type AdminUserStatsParams struct {
	Today time.Time
	Week  time.Time
	Month time.Time
}

type AdminUserStatsRow struct {
	Total        int64
	NewToday     int64
	ActiveToday  int64
	ActiveWeek   int64
	ActiveMonth  int64
	StorageBytes int64
}

// ───────────── 仪表盘 ─────────────
// 用户总数、某时刻之后新增的用户数，以及各时间窗口内有设备活动的用户数。
func (q *Queries) AdminUserStats(ctx context.Context, arg AdminUserStatsParams) (AdminUserStatsRow, error) {
	row := q.db.QueryRow(ctx, adminUserStats, arg.Today, arg.Week, arg.Month)
	var i AdminUserStatsRow
	err := row.Scan(
		&i.Total,
		&i.NewToday,
		&i.ActiveToday,
		&i.ActiveWeek,
		&i.ActiveMonth,
		&i.StorageBytes,
	)
	return i, err
}

const countActiveSuperAdmins = `-- name: CountActiveSuperAdmins :one
SELECT count(*) FROM admin_users WHERE role = 'super_admin' AND NOT disabled
`

func (q *Queries) CountActiveSuperAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSuperAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM admin_audit_logs
WHERE ($1::uuid IS NULL OR admin_id = $1)
  AND ($2::text IS NULL OR action = $2)
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz IS NULL OR created_at < $4)
`

type CountAuditLogsParams struct {
	AdminID *uuid.UUID
	Action  *string
	Since   *time.Time
	Until   *time.Time
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.AdminID,
		arg.Action,
		arg.Since,
		arg.Until,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one


INSERT INTO admin_users (id, username, password_hash, role, must_change_password, password_changed_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $6, $6)
RETURNING id, username, password_hash, role, disabled, must_change_password, failed_logins, locked_until, last_login_at, password_changed_at, created_at, updated_at
`

type CreateAdminParams struct {
	ID                 uuid.UUID
	Username           string
	PasswordHash       string
	Role               string
	MustChangePassword bool
	Now                time.Time
}

// Web 管理后台（ADR-011），由 sqlc 生成到 internal/dbgen（scripts/gen-db.sh）。
// ───────────── 管理员账号 ─────────────
func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.MustChangePassword,
		arg.Now,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.MustChangePassword,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdminSession = `-- name: CreateAdminSession :exec

INSERT INTO admin_sessions (id, admin_id, refresh_hash, created_at, expires_at, last_used_at)
VALUES ($1, $2, $3, $4, $5, $4)
`

type CreateAdminSessionParams struct {
	ID          uuid.UUID
	AdminID     uuid.UUID
	RefreshHash []byte
	Now         time.Time
	ExpiresAt   time.Time
}

// ───────────── 会话 ─────────────
func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) error {
	_, err := q.db.Exec(ctx, createAdminSession,
		arg.ID,
		arg.AdminID,
		arg.RefreshHash,
		arg.Now,
		arg.ExpiresAt,
	)
	return err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, username, password_hash, role, disabled, must_change_password, failed_logins, locked_until, last_login_at, password_changed_at, created_at, updated_at FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdmin(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdmin, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.MustChangePassword,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, role, disabled, must_change_password, failed_logins, locked_until, last_login_at, password_changed_at, created_at, updated_at FROM admin_users WHERE lower(username) = lower($1)
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.MustChangePassword,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminForSession = `-- name: GetAdminForSession :one
SELECT a.id, a.username, a.role, a.must_change_password
FROM admin_sessions s JOIN admin_users a ON a.id = s.admin_id
WHERE s.id = $1 AND s.admin_id = $2 AND s.revoked_at IS NULL AND s.expires_at > $3 AND NOT a.disabled
`

type GetAdminForSessionParams struct {
	SessionID uuid.UUID
	AdminID   uuid.UUID
	Now       time.Time
}

type GetAdminForSessionRow struct {
	ID                 uuid.UUID
	Username           string
	Role               string
	MustChangePassword bool
}

// Access Token 只在会话仍有效时可用：退出、改密码、停用后立即失效。角色与是否须改密码以数据库为准。
func (q *Queries) GetAdminForSession(ctx context.Context, arg GetAdminForSessionParams) (GetAdminForSessionRow, error) {
	row := q.db.QueryRow(ctx, getAdminForSession, arg.SessionID, arg.AdminID, arg.Now)
	var i GetAdminForSessionRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.MustChangePassword,
	)
	return i, err
}

const getAdminForUpdate = `-- name: GetAdminForUpdate :one
SELECT id, username, password_hash, role, disabled, must_change_password, failed_logins, locked_until, last_login_at, password_changed_at, created_at, updated_at FROM admin_users WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAdminForUpdate(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminForUpdate, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.MustChangePassword,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminSessionByHashForUpdate = `-- name: GetAdminSessionByHashForUpdate :one
SELECT id, admin_id, refresh_hash, created_at, expires_at, last_used_at, revoked_at FROM admin_sessions WHERE refresh_hash = $1 FOR UPDATE
`

func (q *Queries) GetAdminSessionByHashForUpdate(ctx context.Context, refreshHash []byte) (AdminSession, error) {
	row := q.db.QueryRow(ctx, getAdminSessionByHashForUpdate, refreshHash)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.RefreshHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec

INSERT INTO admin_audit_logs (id, admin_id, username, action, target_type, target_id, ip, user_agent, detail, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAuditLogParams struct {
	ID         uuid.UUID
	AdminID    *uuid.UUID
	Username   string
	Action     string
	TargetType string
	TargetID   string
	Ip         string
	UserAgent  string
	Detail     []byte
	CreatedAt  time.Time
}

// ───────────── 审计日志 ─────────────
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.AdminID,
		arg.Username,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Ip,
		arg.UserAgent,
		arg.Detail,
		arg.CreatedAt,
	)
	return err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, username, password_hash, role, disabled, must_change_password, failed_logins, locked_until, last_login_at, password_changed_at, created_at, updated_at FROM admin_users ORDER BY created_at
`

func (q *Queries) ListAdmins(ctx context.Context) ([]AdminUser, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUser{}
	for rows.Next() {
		var i AdminUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Disabled,
			&i.MustChangePassword,
			&i.FailedLogins,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, admin_id, username, action, target_type, target_id, ip, user_agent, detail, created_at FROM admin_audit_logs
WHERE ($1::uuid IS NULL OR admin_id = $1)
  AND ($2::text IS NULL OR action = $2)
  AND ($3::timestamptz IS NULL OR created_at >= $3)
  AND ($4::timestamptz IS NULL OR created_at < $4)
ORDER BY created_at DESC, id DESC
LIMIT $6 OFFSET $5
`

type ListAuditLogsParams struct {
	AdminID *uuid.UUID
	Action  *string
	Since   *time.Time
	Until   *time.Time
	Skip    int32
	MaxRows int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.AdminID,
		arg.Action,
		arg.Since,
		arg.Until,
		arg.Skip,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Username,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Ip,
			&i.UserAgent,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAdminSessions = `-- name: PruneAdminSessions :execrows
DELETE FROM admin_sessions WHERE expires_at < $1
`

func (q *Queries) PruneAdminSessions(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAdminSessions, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordAdminLogin = `-- name: RecordAdminLogin :exec
UPDATE admin_users SET failed_logins = 0, locked_until = NULL, last_login_at = $1 WHERE id = $2
`

type RecordAdminLoginParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) RecordAdminLogin(ctx context.Context, arg RecordAdminLoginParams) error {
	_, err := q.db.Exec(ctx, recordAdminLogin, arg.Now, arg.ID)
	return err
}

const recordAdminLoginFailure = `-- name: RecordAdminLoginFailure :one
UPDATE admin_users
SET failed_logins = CASE WHEN failed_logins + 1 >= $1::int THEN 0 ELSE failed_logins + 1 END,
    locked_until = CASE WHEN failed_logins + 1 >= $1::int THEN $2::timestamptz ELSE locked_until END
WHERE id = $3
RETURNING locked_until
`

type RecordAdminLoginFailureParams struct {
	MaxFailures int32
	LockUntil   time.Time
	ID          uuid.UUID
}

// 连续失败达到上限时锁定一段时间，并重新计数。
func (q *Queries) RecordAdminLoginFailure(ctx context.Context, arg RecordAdminLoginFailureParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, recordAdminLoginFailure, arg.MaxFailures, arg.LockUntil, arg.ID)
	var locked_until *time.Time
	err := row.Scan(&locked_until)
	return locked_until, err
}

const revokeAdminSession = `-- name: RevokeAdminSession :exec
UPDATE admin_sessions SET revoked_at = $1 WHERE id = $2 AND revoked_at IS NULL
`

type RevokeAdminSessionParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) RevokeAdminSession(ctx context.Context, arg RevokeAdminSessionParams) error {
	_, err := q.db.Exec(ctx, revokeAdminSession, arg.Now, arg.ID)
	return err
}

const revokeAdminSessions = `-- name: RevokeAdminSessions :exec
UPDATE admin_sessions SET revoked_at = $1 WHERE admin_id = $2 AND revoked_at IS NULL
`

type RevokeAdminSessionsParams struct {
	Now     *time.Time
	AdminID uuid.UUID
}

// 修改或重置密码、停用账号时让该管理员的全部会话失效。
func (q *Queries) RevokeAdminSessions(ctx context.Context, arg RevokeAdminSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAdminSessions, arg.Now, arg.AdminID)
	return err
}

const revokeOtherAdminSessions = `-- name: RevokeOtherAdminSessions :exec
UPDATE admin_sessions SET revoked_at = $1 WHERE admin_id = $2 AND id <> $3 AND revoked_at IS NULL
`

type RevokeOtherAdminSessionsParams struct {
	Now     *time.Time
	AdminID uuid.UUID
	Keep    uuid.UUID
}

// 修改自己的密码时，其他会话失效，当前会话保留。
func (q *Queries) RevokeOtherAdminSessions(ctx context.Context, arg RevokeOtherAdminSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherAdminSessions, arg.Now, arg.AdminID, arg.Keep)
	return err
}

const rotateAdminSession = `-- name: RotateAdminSession :exec
UPDATE admin_sessions SET refresh_hash = $1, last_used_at = $2 WHERE id = $3
`

type RotateAdminSessionParams struct {
	RefreshHash []byte
	Now         time.Time
	ID          uuid.UUID
}

func (q *Queries) RotateAdminSession(ctx context.Context, arg RotateAdminSessionParams) error {
	_, err := q.db.Exec(ctx, rotateAdminSession, arg.RefreshHash, arg.Now, arg.ID)
	return err
}

const setAdminPassword = `-- name: SetAdminPassword :exec
UPDATE admin_users
SET password_hash = $1, must_change_password = $2,
    password_changed_at = $3, failed_logins = 0, locked_until = NULL, updated_at = $3
WHERE id = $4
`

type SetAdminPasswordParams struct {
	PasswordHash       string
	MustChangePassword bool
	Now                time.Time
	ID                 uuid.UUID
}

// 修改或重置密码：同时清除锁定。must_change_password 为 true 表示下次登录必须先改密码（被他人重置时）。
func (q *Queries) SetAdminPassword(ctx context.Context, arg SetAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, setAdminPassword,
		arg.PasswordHash,
		arg.MustChangePassword,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateAdmin = `-- name: UpdateAdmin :one
UPDATE admin_users SET role = $1, disabled = $2, updated_at = $3 WHERE id = $4 RETURNING id, username, password_hash, role, disabled, must_change_password, failed_logins, locked_until, last_login_at, password_changed_at, created_at, updated_at
`

type UpdateAdminParams struct {
	Role     string
	Disabled bool
	Now      time.Time
	ID       uuid.UUID
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, updateAdmin,
		arg.Role,
		arg.Disabled,
		arg.Now,
		arg.ID,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.MustChangePassword,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
