// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exports.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimExport = `-- name: ClaimExport :one
UPDATE exports AS e
SET status = 'running', lease_until = $1::timestamptz, attempts = e.attempts + 1
FROM (
    SELECT x.id FROM exports AS x
    WHERE x.status IN ('pending', 'running')
      AND (x.lease_until IS NULL OR x.lease_until <= $2::timestamptz)
    ORDER BY x.created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
) AS due
WHERE e.id = due.id
RETURNING e.id, e.user_id, e.device_id, e.modules, e.attachments, e.status, e.attempts, e.lease_until, e.object_key, e.size, e.error, e.created_at, e.finished_at, e.expires_at
`

type ClaimExportParams struct {
	LeaseUntil time.Time
	Now        time.Time
}

// 领取一个可以生成的导出（等待中，或生成中但领取已过期），并写回领取期限（调用方在事务内执行）。
func (q *Queries) ClaimExport(ctx context.Context, arg ClaimExportParams) (Export, error) {
	row := q.db.QueryRow(ctx, claimExport, arg.LeaseUntil, arg.Now)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Modules,
		&i.Attachments,
		&i.Status,
		&i.Attempts,
		&i.LeaseUntil,
		&i.ObjectKey,
		&i.Size,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const completeExport = `-- name: CompleteExport :execrows
UPDATE exports
SET status = 'done', object_key = $1, size = $2, finished_at = $3,
    expires_at = $4, lease_until = NULL, error = NULL
WHERE id = $5 AND status = 'running' AND attempts = $6
`

type CompleteExportParams struct {
	ObjectKey  *string
	Size       *int64
	FinishedAt *time.Time
	ExpiresAt  *time.Time
	ID         uuid.UUID
	Attempts   int32
}

// 只有本次领取（attempts 相同）仍然有效时才写入结果：领取过期后已被其他实例重新领取的，以后者为准。
func (q *Queries) CompleteExport(ctx context.Context, arg CompleteExportParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeExport,
		arg.ObjectKey,
		arg.Size,
		arg.FinishedAt,
		arg.ExpiresAt,
		arg.ID,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countExportsSince = `-- name: CountExportsSince :one
SELECT count(*) FROM exports WHERE user_id = $1 AND created_at >= $2
`

type CountExportsSinceParams struct {
	UserID uuid.UUID
	Since  time.Time
}

// 包含用户已删除的导出：删除不能用来绕过次数限制。
func (q *Queries) CountExportsSince(ctx context.Context, arg CountExportsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExportsSince, arg.UserID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExport = `-- name: CreateExport :execrows

INSERT INTO exports (id, user_id, device_id, modules, attachments, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) WHERE status IN ('pending', 'running') DO NOTHING
`

type CreateExportParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	DeviceID    *uuid.UUID
	Modules     []string
	Attachments bool
	CreatedAt   time.Time
}

// 数据导出（ADR-010），由 sqlc 生成到 internal/dbgen（scripts/gen-db.sh）。
// 已有进行中的导出时影响 0 行。
func (q *Queries) CreateExport(ctx context.Context, arg CreateExportParams) (int64, error) {
	result, err := q.db.Exec(ctx, createExport,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.Modules,
		arg.Attachments,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireExport = `-- name: ExpireExport :exec
UPDATE exports SET status = 'expired', object_key = NULL, lease_until = NULL WHERE id = $1 AND status = 'done'
`

func (q *Queries) ExpireExport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, expireExport, id)
	return err
}

const failExport = `-- name: FailExport :execrows
UPDATE exports SET status = 'failed', lease_until = NULL, error = $1, finished_at = $2
WHERE id = $3 AND status = 'running' AND attempts = $4
`

type FailExportParams struct {
	Error      *string
	FinishedAt *time.Time
	ID         uuid.UUID
	Attempts   int32
}

func (q *Queries) FailExport(ctx context.Context, arg FailExportParams) (int64, error) {
	result, err := q.db.Exec(ctx, failExport,
		arg.Error,
		arg.FinishedAt,
		arg.ID,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExport = `-- name: GetExport :one
SELECT id, user_id, device_id, modules, attachments, status, attempts, lease_until, object_key, size, error, created_at, finished_at, expires_at FROM exports WHERE id = $1 AND user_id = $2 AND status <> 'deleted'
`

type GetExportParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetExport(ctx context.Context, arg GetExportParams) (Export, error) {
	row := q.db.QueryRow(ctx, getExport, arg.ID, arg.UserID)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Modules,
		&i.Attachments,
		&i.Status,
		&i.Attempts,
		&i.LeaseUntil,
		&i.ObjectKey,
		&i.Size,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getExportDevice = `-- name: GetExportDevice :one
SELECT push_token, time_zone FROM devices
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type GetExportDeviceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetExportDeviceRow struct {
	PushToken *string
	TimeZone  string
}

// 发起导出的设备：推送标识（可能为空）与时区。已退出登录的设备查不到。
func (q *Queries) GetExportDevice(ctx context.Context, arg GetExportDeviceParams) (GetExportDeviceRow, error) {
	row := q.db.QueryRow(ctx, getExportDevice, arg.ID, arg.UserID)
	var i GetExportDeviceRow
	err := row.Scan(&i.PushToken, &i.TimeZone)
	return i, err
}

const getExportStatus = `-- name: GetExportStatus :one
SELECT status FROM exports WHERE id = $1
`

// 后台任务核对导出是否仍在（账号可能已注销）。
func (q *Queries) GetExportStatus(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getExportStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listExpiredExports = `-- name: ListExpiredExports :many
SELECT id, object_key FROM exports
WHERE status = 'done' AND expires_at <= $1
ORDER BY expires_at
LIMIT $2
`

type ListExpiredExportsParams struct {
	Now     *time.Time
	MaxRows int32
}

type ListExpiredExportsRow struct {
	ID        uuid.UUID
	ObjectKey *string
}

func (q *Queries) ListExpiredExports(ctx context.Context, arg ListExpiredExportsParams) ([]ListExpiredExportsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredExports, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredExportsRow{}
	for rows.Next() {
		var i ListExpiredExportsRow
		if err := rows.Scan(&i.ID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExports = `-- name: ListExports :many
SELECT id, user_id, device_id, modules, attachments, status, attempts, lease_until, object_key, size, error, created_at, finished_at, expires_at FROM exports WHERE user_id = $1 AND status <> 'deleted' ORDER BY created_at DESC LIMIT $2
`

type ListExportsParams struct {
	UserID  uuid.UUID
	MaxRows int32
}

func (q *Queries) ListExports(ctx context.Context, arg ListExportsParams) ([]Export, error) {
	rows, err := q.db.Query(ctx, listExports, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Export{}
	for rows.Next() {
		var i Export
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.Modules,
			&i.Attachments,
			&i.Status,
			&i.Attempts,
			&i.LeaseUntil,
			&i.ObjectKey,
			&i.Size,
			&i.Error,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushTokens = `-- name: ListPushTokens :many
SELECT push_token::text FROM devices
WHERE user_id = $1 AND revoked_at IS NULL AND push_token IS NOT NULL
`

// 账号所有已登录设备的推送标识：导出完成时都通知，其他设备也能知道发生了导出。
func (q *Queries) ListPushTokens(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPushTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var push_token string
		if err := rows.Scan(&push_token); err != nil {
			return nil, err
		}
		items = append(items, push_token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyAttachments = `-- name: ListReadyAttachments :many
SELECT id, object_key, size FROM attachments WHERE user_id = $1 AND status = 'ready'
`

type ListReadyAttachmentsRow struct {
	ID        uuid.UUID
	ObjectKey string
	Size      int64
}

func (q *Queries) ListReadyAttachments(ctx context.Context, userID uuid.UUID) ([]ListReadyAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listReadyAttachments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadyAttachmentsRow{}
	for rows.Next() {
		var i ListReadyAttachmentsRow
		if err := rows.Scan(&i.ID, &i.ObjectKey, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRecords = `-- name: ListUserRecords :many
SELECT id, user_id, entity, version, server_seq, fields, clocks, absorbed, deleted, device_id, created_at, updated_at FROM records
WHERE user_id = $1 AND NOT deleted AND entity = ANY($2::text[]) AND server_seq > $3
ORDER BY server_seq
LIMIT $4
`

type ListUserRecordsParams struct {
	UserID   uuid.UUID
	Entities []string
	After    int64
	MaxRows  int32
}

// 逐页读取账号的有效记录（不含墓碑），按同步序号翻页。
func (q *Queries) ListUserRecords(ctx context.Context, arg ListUserRecordsParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, listUserRecords,
		arg.UserID,
		arg.Entities,
		arg.After,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Entity,
			&i.Version,
			&i.ServerSeq,
			&i.Fields,
			&i.Clocks,
			&i.Absorbed,
			&i.Deleted,
			&i.DeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExportDeleted = `-- name: MarkExportDeleted :execrows
UPDATE exports SET status = 'deleted', object_key = NULL, lease_until = NULL
WHERE id = $1 AND user_id = $2 AND status IN ('done', 'failed', 'expired')
`

type MarkExportDeletedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// 用户删除导出（文件已由调用方删除）。进行中的不能删除。
func (q *Queries) MarkExportDeleted(ctx context.Context, arg MarkExportDeletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markExportDeleted, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneExports = `-- name: PruneExports :execrows
DELETE FROM exports WHERE status IN ('failed', 'expired', 'deleted') AND created_at < $1
`

// 已结束且文件已不存在的导出记录保留一段时间供查看，之后删除（须长于 24 小时，以免影响次数限制）。
func (q *Queries) PruneExports(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneExports, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseExport = `-- name: ReleaseExport :exec
UPDATE exports SET status = 'pending', lease_until = NULL, attempts = attempts - 1
WHERE id = $1 AND status = 'running' AND attempts = $2
`

type ReleaseExportParams struct {
	ID       uuid.UUID
	Attempts int32
}

// 服务停止时交还未完成的领取：立即可以重新领取，本次不计入尝试次数。
func (q *Queries) ReleaseExport(ctx context.Context, arg ReleaseExportParams) error {
	_, err := q.db.Exec(ctx, releaseExport, arg.ID, arg.Attempts)
	return err
}

const retryExport = `-- name: RetryExport :execrows
UPDATE exports SET status = 'pending', lease_until = $1, error = $2
WHERE id = $3 AND status = 'running' AND attempts = $4
`

type RetryExportParams struct {
	RetryAt  *time.Time
	Error    *string
	ID       uuid.UUID
	Attempts int32
}

func (q *Queries) RetryExport(ctx context.Context, arg RetryExportParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryExport,
		arg.RetryAt,
		arg.Error,
		arg.ID,
		arg.Attempts,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
