// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type Device struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	InstallationID   string
	Platform         string
	Model            string
	OsVersion        string
	AppVersion       string
	RefreshHash      []byte
	RefreshPrevHash  []byte
	RefreshRotatedAt *time.Time
	RefreshExpiresAt *time.Time
	LastIp           string
	LastActiveAt     time.Time
	CreatedAt        time.Time
	TokensValidAfter time.Time
	RevokedAt        *time.Time
}

type User struct {
	ID                uuid.UUID
	Username          string
	Nickname          string
	Phone             *string
	PasswordHash      string
	PasswordChangedAt time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type UserSetting struct {
	UserID           uuid.UUID
	ThemeMode        string
	FontScale        float32
	DefaultReminders []int32
	WeekStart        int16
	UpdatedAt        time.Time
}
