// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type AdminAuditLog struct {
	ID         uuid.UUID
	AdminID    *uuid.UUID
	Username   string
	Action     string
	TargetType string
	TargetID   string
	Ip         string
	UserAgent  string
	Detail     []byte
	CreatedAt  time.Time
}

type AdminSession struct {
	ID          uuid.UUID
	AdminID     uuid.UUID
	RefreshHash []byte
	CreatedAt   time.Time
	ExpiresAt   time.Time
	LastUsedAt  time.Time
	RevokedAt   *time.Time
}

type AdminUser struct {
	ID                 uuid.UUID
	Username           string
	PasswordHash       string
	Role               string
	Disabled           bool
	MustChangePassword bool
	FailedLogins       int32
	LockedUntil        *time.Time
	LastLoginAt        *time.Time
	PasswordChangedAt  time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Attachment struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	OwnerEntity string
	OwnerID     uuid.UUID
	ObjectKey   string
	FileName    string
	Mime        string
	Size        int64
	Sha256      string
	Status      string
	CreatedAt   time.Time
	CompletedAt *time.Time
}

type Device struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	InstallationID   string
	Platform         string
	Model            string
	OsVersion        string
	AppVersion       string
	RefreshHash      []byte
	RefreshPrevHash  []byte
	RefreshRotatedAt *time.Time
	RefreshExpiresAt *time.Time
	LastIp           string
	LastActiveAt     time.Time
	CreatedAt        time.Time
	TokensValidAfter time.Time
	RevokedAt        *time.Time
	LastAckSeq       int64
	PushProvider     *string
	PushToken        *string
	TimeZone         string
	LocalReminders   bool
	LocalUntil       *time.Time
}

type Export struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	DeviceID    *uuid.UUID
	Modules     []string
	Attachments bool
	Status      string
	Attempts    int32
	LeaseUntil  *time.Time
	ObjectKey   *string
	Size        *int64
	Error       *string
	CreatedAt   time.Time
	FinishedAt  *time.Time
	ExpiresAt   *time.Time
}

type MemoReminder struct {
	MemoID     uuid.UUID
	UserID     uuid.UUID
	OffsetMin  int32
	FireAt     time.Time
	LeaseUntil *time.Time
	Attempts   int32
}

type Record struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Entity    string
	Version   int64
	ServerSeq int64
	Fields    []byte
	Clocks    []byte
	Absorbed  []byte
	Deleted   bool
	DeviceID  *uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RecordRevision struct {
	ID        uuid.UUID
	RecordID  uuid.UUID
	UserID    uuid.UUID
	Entity    string
	Version   int64
	Reason    string
	Fields    []byte
	DeviceID  *uuid.UUID
	CreatedAt time.Time
}

type SyncCursor struct {
	UserID  uuid.UUID
	LastSeq int64
}

type User struct {
	ID                uuid.UUID
	Username          string
	Nickname          string
	Phone             *string
	PasswordHash      string
	PasswordChangedAt time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type UserKey struct {
	UserID    uuid.UUID
	KmsKeyID  string
	Wrapped   []byte
	CreatedAt time.Time
}

type UserSetting struct {
	UserID           uuid.UUID
	ThemeMode        string
	FontScale        float32
	DefaultReminders []int32
	WeekStart        int16
	UpdatedAt        time.Time
}
