// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const ackDevice = `-- name: AckDevice :execrows
UPDATE devices SET last_ack_seq = GREATEST(last_ack_seq, $1)
WHERE id = $2 AND user_id = $3 AND revoked_at IS NULL
`

type AckDeviceParams struct {
	Seq    int64
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) AckDevice(ctx context.Context, arg AckDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, ackDevice, arg.Seq, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPendingAttachments = `-- name: CountPendingAttachments :one
SELECT count(*)::bigint AS n FROM attachments WHERE user_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingAttachments(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingAttachments, userID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const expirePendingAttachments = `-- name: ExpirePendingAttachments :execrows
UPDATE attachments SET status = 'deleted' WHERE status = 'pending' AND created_at < $1
`

// 申请后一直未完成的上传视为放弃，交给清理任务删除对象并释放配额。
func (q *Queries) ExpirePendingAttachments(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, expirePendingAttachments, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, user_id, owner_entity, owner_id, object_key, file_name, mime, size, sha256, status, created_at, completed_at FROM attachments WHERE id = $1 AND user_id = $2
`

type GetAttachmentParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, arg.ID, arg.UserID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OwnerEntity,
		&i.OwnerID,
		&i.ObjectKey,
		&i.FileName,
		&i.Mime,
		&i.Size,
		&i.Sha256,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAttachmentForUpdate = `-- name: GetAttachmentForUpdate :one
SELECT id, user_id, owner_entity, owner_id, object_key, file_name, mime, size, sha256, status, created_at, completed_at FROM attachments WHERE id = $1 AND user_id = $2 FOR UPDATE
`

type GetAttachmentForUpdateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAttachmentForUpdate(ctx context.Context, arg GetAttachmentForUpdateParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentForUpdate, arg.ID, arg.UserID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OwnerEntity,
		&i.OwnerID,
		&i.ObjectKey,
		&i.FileName,
		&i.Mime,
		&i.Size,
		&i.Sha256,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRecord = `-- name: GetRecord :one
SELECT id, user_id, entity, version, server_seq, fields, clocks, absorbed, deleted, device_id, created_at, updated_at FROM records WHERE id = $1 AND user_id = $2
`

type GetRecordParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRecord(ctx context.Context, arg GetRecordParams) (Record, error) {
	row := q.db.QueryRow(ctx, getRecord, arg.ID, arg.UserID)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Entity,
		&i.Version,
		&i.ServerSeq,
		&i.Fields,
		&i.Clocks,
		&i.Absorbed,
		&i.Deleted,
		&i.DeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecordForUpdate = `-- name: GetRecordForUpdate :one
SELECT id, user_id, entity, version, server_seq, fields, clocks, absorbed, deleted, device_id, created_at, updated_at FROM records WHERE id = $1 AND user_id = $2 FOR UPDATE
`

type GetRecordForUpdateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// 只锁当前账号的行，避免与其他账号产生锁等待。
func (q *Queries) GetRecordForUpdate(ctx context.Context, arg GetRecordForUpdateParams) (Record, error) {
	row := q.db.QueryRow(ctx, getRecordForUpdate, arg.ID, arg.UserID)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Entity,
		&i.Version,
		&i.ServerSeq,
		&i.Fields,
		&i.Clocks,
		&i.Absorbed,
		&i.Deleted,
		&i.DeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRevision = `-- name: GetRevision :one
SELECT id, record_id, user_id, entity, version, reason, fields, device_id, created_at FROM record_revisions WHERE id = $1 AND user_id = $2
`

type GetRevisionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRevision(ctx context.Context, arg GetRevisionParams) (RecordRevision, error) {
	row := q.db.QueryRow(ctx, getRevision, arg.ID, arg.UserID)
	var i RecordRevision
	err := row.Scan(
		&i.ID,
		&i.RecordID,
		&i.UserID,
		&i.Entity,
		&i.Version,
		&i.Reason,
		&i.Fields,
		&i.DeviceID,
		&i.CreatedAt,
	)
	return i, err
}

const getSyncCursor = `-- name: GetSyncCursor :one
SELECT COALESCE((SELECT last_seq FROM sync_cursors WHERE user_id = $1), 0)::bigint AS last_seq
`

func (q *Queries) GetSyncCursor(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getSyncCursor, userID)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const getUserKey = `-- name: GetUserKey :one
SELECT user_id, kms_key_id, wrapped, created_at FROM user_keys WHERE user_id = $1
`

func (q *Queries) GetUserKey(ctx context.Context, userID uuid.UUID) (UserKey, error) {
	row := q.db.QueryRow(ctx, getUserKey, userID)
	var i UserKey
	err := row.Scan(
		&i.UserID,
		&i.KmsKeyID,
		&i.Wrapped,
		&i.CreatedAt,
	)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :exec
INSERT INTO attachments (id, user_id, owner_entity, owner_id, object_key, file_name, mime, size, sha256)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAttachmentParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	OwnerEntity string
	OwnerID     uuid.UUID
	ObjectKey   string
	FileName    string
	Mime        string
	Size        int64
	Sha256      string
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertAttachment,
		arg.ID,
		arg.UserID,
		arg.OwnerEntity,
		arg.OwnerID,
		arg.ObjectKey,
		arg.FileName,
		arg.Mime,
		arg.Size,
		arg.Sha256,
	)
	return err
}

const insertRecord = `-- name: InsertRecord :execrows
INSERT INTO records (id, user_id, entity, version, server_seq, fields, clocks, absorbed, deleted, device_id)
VALUES ($1, $2, $3, 1, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO NOTHING
`

type InsertRecordParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Entity    string
	ServerSeq int64
	Fields    []byte
	Clocks    []byte
	Absorbed  []byte
	Deleted   bool
	DeviceID  *uuid.UUID
}

// 两个账号并发插入同一 ID 时，后到者影响 0 行，由调用方报告 ID 冲突。
func (q *Queries) InsertRecord(ctx context.Context, arg InsertRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRecord,
		arg.ID,
		arg.UserID,
		arg.Entity,
		arg.ServerSeq,
		arg.Fields,
		arg.Clocks,
		arg.Absorbed,
		arg.Deleted,
		arg.DeviceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRevision = `-- name: InsertRevision :exec
INSERT INTO record_revisions (id, record_id, user_id, entity, version, reason, fields, device_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRevisionParams struct {
	ID       uuid.UUID
	RecordID uuid.UUID
	UserID   uuid.UUID
	Entity   string
	Version  int64
	Reason   string
	Fields   []byte
	DeviceID *uuid.UUID
}

func (q *Queries) InsertRevision(ctx context.Context, arg InsertRevisionParams) error {
	_, err := q.db.Exec(ctx, insertRevision,
		arg.ID,
		arg.RecordID,
		arg.UserID,
		arg.Entity,
		arg.Version,
		arg.Reason,
		arg.Fields,
		arg.DeviceID,
	)
	return err
}

const insertUserKey = `-- name: InsertUserKey :exec
INSERT INTO user_keys (user_id, kms_key_id, wrapped) VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO NOTHING
`

type InsertUserKeyParams struct {
	UserID   uuid.UUID
	KmsKeyID string
	Wrapped  []byte
}

// 并发创建时以先写入者为准，调用方随后重新读取。
func (q *Queries) InsertUserKey(ctx context.Context, arg InsertUserKeyParams) error {
	_, err := q.db.Exec(ctx, insertUserKey, arg.UserID, arg.KmsKeyID, arg.Wrapped)
	return err
}

const listDeletedAttachments = `-- name: ListDeletedAttachments :many
SELECT id, object_key FROM attachments WHERE status = 'deleted' ORDER BY created_at LIMIT $1
`

type ListDeletedAttachmentsRow struct {
	ID        uuid.UUID
	ObjectKey string
}

func (q *Queries) ListDeletedAttachments(ctx context.Context, maxRows int32) ([]ListDeletedAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listDeletedAttachments, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedAttachmentsRow{}
	for rows.Next() {
		var i ListDeletedAttachmentsRow
		if err := rows.Scan(&i.ID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordsSince = `-- name: ListRecordsSince :many
SELECT id, user_id, entity, version, server_seq, fields, clocks, absorbed, deleted, device_id, created_at, updated_at FROM records
WHERE user_id = $1 AND server_seq > $2
ORDER BY server_seq
LIMIT $3
`

type ListRecordsSinceParams struct {
	UserID  uuid.UUID
	Since   int64
	MaxRows int32
}

func (q *Queries) ListRecordsSince(ctx context.Context, arg ListRecordsSinceParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, listRecordsSince, arg.UserID, arg.Since, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Entity,
			&i.Version,
			&i.ServerSeq,
			&i.Fields,
			&i.Clocks,
			&i.Absorbed,
			&i.Deleted,
			&i.DeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisions = `-- name: ListRevisions :many
SELECT r.id, r.version, r.reason, r.created_at, r.device_id, COALESCE(d.model, '')::text AS device_model
FROM record_revisions r
LEFT JOIN devices d ON d.id = r.device_id
WHERE r.record_id = $1 AND r.user_id = $2
ORDER BY r.created_at DESC, r.id DESC
`

type ListRevisionsParams struct {
	RecordID uuid.UUID
	UserID   uuid.UUID
}

type ListRevisionsRow struct {
	ID          uuid.UUID
	Version     int64
	Reason      string
	CreatedAt   time.Time
	DeviceID    *uuid.UUID
	DeviceModel string
}

func (q *Queries) ListRevisions(ctx context.Context, arg ListRevisionsParams) ([]ListRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listRevisions, arg.RecordID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRevisionsRow{}
	for rows.Next() {
		var i ListRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Reason,
			&i.CreatedAt,
			&i.DeviceID,
			&i.DeviceModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSyncCursor = `-- name: LockSyncCursor :one

INSERT INTO sync_cursors (user_id) VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET last_seq = sync_cursors.last_seq
RETURNING last_seq
`

// 同步、修订历史、数据密钥与附件相关查询，由 sqlc 生成到 internal/dbgen（scripts/gen-db.sh）。
// 取得（必要时创建）账号的同步游标并加行锁，同一账号的推送因此串行。
func (q *Queries) LockSyncCursor(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, lockSyncCursor, userID)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const markAttachmentDeleted = `-- name: MarkAttachmentDeleted :exec
UPDATE attachments SET status = 'deleted' WHERE id = $1 AND user_id = $2
`

type MarkAttachmentDeletedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkAttachmentDeleted(ctx context.Context, arg MarkAttachmentDeletedParams) error {
	_, err := q.db.Exec(ctx, markAttachmentDeleted, arg.ID, arg.UserID)
	return err
}

const markAttachmentReady = `-- name: MarkAttachmentReady :exec
UPDATE attachments SET status = 'ready', completed_at = now() WHERE id = $1
`

func (q *Queries) MarkAttachmentReady(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAttachmentReady, id)
	return err
}

const pruneRevisions = `-- name: PruneRevisions :exec
DELETE FROM record_revisions AS old
WHERE old.record_id = $1::uuid
  AND old.id NOT IN (
    SELECT r.id FROM record_revisions AS r WHERE r.record_id = $1::uuid
    ORDER BY r.created_at DESC, r.id DESC LIMIT $2
  )
`

type PruneRevisionsParams struct {
	RecordID uuid.UUID
	Keep     int32
}

// 每条记录最多保留最近 @keep 份修订。
func (q *Queries) PruneRevisions(ctx context.Context, arg PruneRevisionsParams) error {
	_, err := q.db.Exec(ctx, pruneRevisions, arg.RecordID, arg.Keep)
	return err
}

const purgeAttachment = `-- name: PurgeAttachment :exec
DELETE FROM attachments WHERE id = $1 AND status = 'deleted'
`

func (q *Queries) PurgeAttachment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, purgeAttachment, id)
	return err
}

const recordIDTaken = `-- name: RecordIDTaken :one
SELECT EXISTS (SELECT 1 FROM records WHERE id = $1)::boolean AS taken
`

// ID 是否已被使用（任意账号）。不加锁，只用于判断 ID 冲突。
func (q *Queries) RecordIDTaken(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, recordIDTaken, id)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const setSyncCursor = `-- name: SetSyncCursor :exec
UPDATE sync_cursors SET last_seq = $1 WHERE user_id = $2
`

type SetSyncCursorParams struct {
	LastSeq int64
	UserID  uuid.UUID
}

func (q *Queries) SetSyncCursor(ctx context.Context, arg SetSyncCursorParams) error {
	_, err := q.db.Exec(ctx, setSyncCursor, arg.LastSeq, arg.UserID)
	return err
}

const sumAttachmentBytes = `-- name: SumAttachmentBytes :one
SELECT COALESCE(SUM(size), 0)::bigint AS total FROM attachments WHERE user_id = $1 AND status <> 'deleted'
`

func (q *Queries) SumAttachmentBytes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumAttachmentBytes, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateRecord = `-- name: UpdateRecord :exec
UPDATE records
SET version = version + 1, server_seq = $1, fields = $2, clocks = $3,
    absorbed = $4, deleted = $5, device_id = $6, updated_at = now()
WHERE id = $7
`

type UpdateRecordParams struct {
	ServerSeq int64
	Fields    []byte
	Clocks    []byte
	Absorbed  []byte
	Deleted   bool
	DeviceID  *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) error {
	_, err := q.db.Exec(ctx, updateRecord,
		arg.ServerSeq,
		arg.Fields,
		arg.Clocks,
		arg.Absorbed,
		arg.Deleted,
		arg.DeviceID,
		arg.ID,
	)
	return err
}
